"""add rate_limits table

Revision ID: f0197406eff9
Revises: baeeaa5b9415
Create Date: 2026-07-02 09:38:52.022887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0197406eff9'
down_revision: Union[str, None] = 'baeeaa5b9415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
